### ISSUE TITLE
Missing ch11 code files.

### ISSUE THREAD

**Issue by WillieMaddox** [mdiener21/python-geospatial-analysis-cookbook#2]
Hello,
I recently purchased your book and am now working my way through Chapter 11.  On page 267, steps 1 and 2 import shapefiles e01_room_data.shp and e02_room_data.shp, respectively.  However, I am unable to locate these files.  Do you know how I might get (or generate) them?
Thanks,

**Comment by mdiener21** [comment]
@WillieMaddox  Hi wow, big sorry for that.  I have pushed the folder to git  /ch11/geodata  

please let me know if you have any questions.
cheers
Michael
