### ISSUE TITLE
Question on the file 

### ISSUE THREAD

**Issue by Rashid-S** [mdiener21/python-geospatial-analysis-cookbook#3]
Dear Michael,

I have a question on the file ch07-02_elev_profile.py. What do the numbers at the input of LineString mean? - [(-13659328.8483806, 6450545.73152317), (-13651422.7820022, 6466228.25663444)].

**Comment by mdiener21** [comment]
Hi Rashid,
`line = LineString([(-13659328.8483806, 6450545.73152317), (-13651422.7820022, 6466228.25663444)])`

These 2 coordinates represent the two points of the line..ie the linestring is made of only two points.

Feel free to send me any other questions.

**Comment by Rashid-S** [comment]
In general, coordinates are written for example like this: 59.991021 °, 45.801719 ° - if in degrees.

Maybe I did not understand something completely?

**Comment by Rashid-S** [comment]
In general, coordinates are written for example like this: 59.991021 °, 45.801719 ° - if in degrees.

Maybe I did not understand something completely?

**Comment by mdiener21** [comment]
the answer is, it all depends on the coordinate system of the data.  If you have your data in EPSG:4326  ie decimal degrees you will have coordinates that look like the ones you wrote above.  The coordinates I have provided in my book are all in the  [EPSG: 3857](http://epsg.io/3857)  and therefor are negative and well large.

I hope that clears things up for you.

**Comment by Rashid-S** [comment]
Here's how! I did not even know that. In general, from geodesy is a bit far.

Such question, and it is possible in your code to set any geographical coordinates to build a terrain profile? And what is needed for this?

**Comment by mdiener21** [comment]
To build a terrain profile you will need two things: 1. elevation model and 2. a linestring
  you can read in Chapter 7 "creating an elevation profile"   The process involves extracting the z elevation values from the elevation model to your linestring

**Comment by Rashid-S** [comment]
Can I not use the file "ch07-02_elev_profile.py"? To enter there coordinates of interest to me, having preliminary recalculated them in EPSG: 3857?

**Comment by mdiener21** [comment]
yes of course but this will only generate a profile with the data I have provided.  If you want to make your own you will need substitute in your own raster elevation data and linestring.

**Comment by mdiener21** [comment]
Note you could use #mapzen elevation service for world wide elevation data coverage [mapzen elevation](https://mapzen.com/documentation/elevation/elevation-service/)

**Comment by Rashid-S** [comment]
You want to say that I need to create my own file "dem_3857.dem" using the code in the file "ch07-01_dem2postgis.py"? I'm in geodesy and programming novices, sorry)))

**Comment by mdiener21** [comment]
No,  if you want to use your own dataset for some other location you will need to go online and find a DEM file for the location of interest.  Download that DEM file, check its coordinate system then you must create your own linestring in the correct coordinate system.  Then you must modify my code example from Ch07.    01_dem2postgis.py  will not help you.

**Comment by Rashid-S** [comment]
It's not as simple as I thought.

**Comment by Rashid-S** [comment]
It's not as simple as I thought. You did all this on the Python?

**Comment by mdiener21** [comment]
yes all was done in Python.  My background is GIS (Geoinformation Systems), geodesy, geography and IT.  Your task is quite common, if you don't want to code it up, just use a desktop GIS software like Quantum GIS  www.qgis.org and download the plugin Profile  to create the profile...you still however need to get the DEM and the linestring.

**Comment by Rashid-S** [comment]
Michael, and you can help me in getting a DEM. How to do it? Did you describe this in your book "Python Geospatial Analysis Cookbook"?

P.s.: Sorry for my knowledge of English.

**Comment by mdiener21** [comment]
Rashid, sorry but finding and getting a DEM for your project is your job and not part of my book.  You will have to do some searching.
