### ISSUE TITLE
QhullError

### ISSUE THREAD

**Issue by simGudim** [mdiener21/python-geospatial-analysis-cookbook#4]
Hello, 

Thank you for your hard work with this module. I am trying to get the centreline of a complex polygon and I am getting the following error:
QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)

I was wondering if you would know what to do about this issue.

Thanks

**Comment by mdiener21** [comment]
sorry never recieved the github message :(  .      Sounds like you have polygons with less than 4 nodes.   By definition a polygon is valid with a min of 4 nodes where the first node xy is same as the last xy.   Validated your data and try again.

Sorry for the super duper late reply
